<a href="https://colab.research.google.com/github/tripathiarpan20/US-Transporter-eval/blob/main/US_Transporter_eval.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%cd /content/
!git clone --recursive https://github.com/tripathiarpan20/US-Transporter-eval.git
%cd US-Transporter-eval
!pip install -r requirements.txt
!mv phasepack/phasepack/* phasepack/

/content
Cloning into 'US-Transporter-eval'...
remote: Enumerating objects: 46, done.
remote: Counting objects: 100% (46/46), done.
remote: Compressing objects: 100% (33/33), done.
remote: Total 46 (delta 17), reused 27 (delta 9), pack-reused 0
Unpacking objects: 100% (46/46), done.
Submodule 'phasepack' (https://github.com/alimuldal/phasepack.git) registered for path 'phasepack'
Submodule 'pyssim' (https://github.com/jterrace/pyssim.git) registered for path 'pyssim'
Cloning into '/content/US-Transporter-eval/phasepack'...
remote: Enumerating objects: 74, done.        
remote: Total 74 (delta 0), reused 0 (delta 0), pack-reused 74        
Cloning into '/content/US-Transporter-eval/pyssim'...
remote: Enumerating objects: 238, done.        
remote: Total 238 (delta 0), reused 0 (delta 0), pack-reused 238        
Receiving objects: 100% (238/238), 2.57 MiB | 20.75 MiB/s, done.
Resolving deltas: 100% (119/119), done.
Submodule path 'phasepack': checked out 'a7eaf26f4bd91b6cb7e3ac6cb93e9fd1

In [ ]:
#LUS weighted 
!gdown --id 1HBuTOm_5-p7VrpYWYYPoJp2epQvbyPl9

#WUS weighted
!gdown --id 1TMMNh6Vp07ejBDInsar5wXhljs9q7T57

Downloading...
From: https://drive.google.com/uc?id=1HBuTOm_5-p7VrpYWYYPoJp2epQvbyPl9
To: /content/US-Transporter-eval/ckpt_TPRv1_LUS_radonbpm_lr0.0001_LUS_nossim_dptdecay_samrate10_VER_HORIZ_weightedHlam_radonbpm_-epoch=59-val_loss=0.00012.ckpt
11.0MB [00:00, 67.4MB/s]
Downloading...
From: https://drive.google.com/uc?id=1TMMNh6Vp07ejBDInsar5wXhljs9q7T57
To: /content/US-Transporter-eval/wrist_ckpt_TPRv1_lr0.0001_idxcsv_dptdecay_samrate=10_weightedHlam_15+3j_radon&bpm_-epoch=59-val_loss=0.00017.ckpt
11.0MB [00:00, 66.9MB/s]


In [ ]:
#LUS sample data
!gdown --id 11ZRVaMatUbYDI7IhK-Boq1yVWcKQHm8b

#WUS sample data
!gdown --id 1XTrF7wW8wxWLkNT6ZC9xHeh6uQl2rQTa


Downloading...
From: https://drive.google.com/uc?id=11ZRVaMatUbYDI7IhK-Boq1yVWcKQHm8b
To: /content/US-Transporter-eval/LUS.zip
4.83MB [00:00, 15.4MB/s]
Downloading...
From: https://drive.google.com/uc?id=1XTrF7wW8wxWLkNT6ZC9xHeh6uQl2rQTa
To: /content/US-Transporter-eval/WUS.zip
100% 705k/705k [00:00<00:00, 45.5MB/s]


In [ ]:
!unzip LUS.zip -d LUS/

Archive:  LUS.zip
  inflating: LUS/13089_2020_185_Fig3_HTML.jpg  
  inflating: LUS/B-lines-and-lung-rockets-Typical-multiple-B-lines-This-figure-shows-the-7-features-of_Q640.jpg  
  inflating: LUS/Vid18.mp4           


In [ ]:
!unzip WUS.zip -d WUS/

Archive:  WUS.zip
  inflating: WUS/011-wristDorSag-31L-5.mp4  


In [ ]:
!python eval_LUS.py --vid '/content/US-Transporter-eval/LUS/Vid18.mp4' --frame_no 50 --device 'cpu' --ckpt '/content/US-Transporter-eval/ckpt_TPRv1_LUS_radonbpm_lr0.0001_LUS_nossim_dptdecay_samrate10_VER_HORIZ_weightedHlam_radonbpm_-epoch=59-val_loss=0.00012.ckpt'

importing ssim
imported ssim
importing torchradon
imported torchradon
Check 1
Namespace(ckpt='/content/US-Transporter-eval/ckpt_TPRv1_LUS_radonbpm_lr0.0001_LUS_nossim_dptdecay_samrate10_VER_HORIZ_weightedHlam_radonbpm_-epoch=59-val_loss=0.00012.ckpt', device='cpu', frame_no=50, img='', vid='/content/US-Transporter-eval/LUS/Vid18.mp4')
Initial Hlam weights are: Parameter containing:
tensor([[[[0.1000]],

         [[0.1000]],

         [[0.1000]],

         [[0.1000]],

         [[0.1000]],

         [[0.1000]],

         [[0.1000]],

         [[0.1000]],

         [[0.1000]],

         [[0.1000]]]], requires_grad=True)
torch.Size([3, 256, 256])
torch.Size([3, 256, 256])
torch.Size([3, 256, 256])
returned
recieved_vid_frame
output/frame50Vid18.jpg


In [ ]:
!python eval_LUS.py --img '/content/US-Transporter-eval/LUS/B-lines-and-lung-rockets-Typical-multiple-B-lines-This-figure-shows-the-7-features-of_Q640.jpg' --device 'cpu' --ckpt '/content/US-Transporter-eval/ckpt_TPRv1_LUS_radonbpm_lr0.0001_LUS_nossim_dptdecay_samrate10_VER_HORIZ_weightedHlam_radonbpm_-epoch=59-val_loss=0.00012.ckpt'

importing ssim
imported ssim
importing torchradon
imported torchradon
Check 1
Namespace(ckpt='/content/US-Transporter-eval/ckpt_TPRv1_LUS_radonbpm_lr0.0001_LUS_nossim_dptdecay_samrate10_VER_HORIZ_weightedHlam_radonbpm_-epoch=59-val_loss=0.00012.ckpt', device='cpu', frame_no=-1, img='/content/US-Transporter-eval/LUS/B-lines-and-lung-rockets-Typical-multiple-B-lines-This-figure-shows-the-7-features-of_Q640.jpg', vid='')
Initial Hlam weights are: Parameter containing:
tensor([[[[0.1000]],

         [[0.1000]],

         [[0.1000]],

         [[0.1000]],

         [[0.1000]],

         [[0.1000]],

         [[0.1000]],

         [[0.1000]],

         [[0.1000]],

         [[0.1000]]]], requires_grad=True)
(515, 515)
torch.Size([1, 256, 256])
torch.Size([3, 256, 256])
torch.Size([3, 256, 256])
returned
recieved_img
output/B-lines-and-lung-rockets-Typical-multiple-B-lines-This-figure-shows-the-7-features-of_Q640.jpg


In [ ]:
!python eval_LUS.py --img '/content/US-Transporter-eval/LUS/13089_2020_185_Fig3_HTML.jpg' --device 'cpu' --ckpt '/content/US-Transporter-eval/ckpt_TPRv1_LUS_radonbpm_lr0.0001_LUS_nossim_dptdecay_samrate10_VER_HORIZ_weightedHlam_radonbpm_-epoch=59-val_loss=0.00012.ckpt'

importing ssim
imported ssim
importing torchradon
imported torchradon
Check 1
Namespace(ckpt='/content/US-Transporter-eval/ckpt_TPRv1_LUS_radonbpm_lr0.0001_LUS_nossim_dptdecay_samrate10_VER_HORIZ_weightedHlam_radonbpm_-epoch=59-val_loss=0.00012.ckpt', device='cpu', frame_no=-1, img='/content/US-Transporter-eval/LUS/13089_2020_185_Fig3_HTML.jpg', vid='')
Initial Hlam weights are: Parameter containing:
tensor([[[[0.1000]],

         [[0.1000]],

         [[0.1000]],

         [[0.1000]],

         [[0.1000]],

         [[0.1000]],

         [[0.1000]],

         [[0.1000]],

         [[0.1000]],

         [[0.1000]]]], requires_grad=True)
(604, 685, 3)
torch.Size([1, 256, 256])
torch.Size([3, 256, 256])
torch.Size([3, 256, 256])
returned
recieved_img
output/13089_2020_185_Fig3_HTML.jpg


In [ ]:
!python eval_WUS.py --vid '/content/US-Transporter-eval/WUS/011-wristDorSag-31L-5.mp4' --frame_no 60 --device 'cpu' --ckpt '/content/US-Transporter-eval/ckpt_TPRv1_LUS_radonbpm_lr0.0001_LUS_nossim_dptdecay_samrate10_VER_HORIZ_weightedHlam_radonbpm_-epoch=59-val_loss=0.00012.ckpt'

importing ssim
imported ssim
importing torchradon
imported torchradon
Check 1
Namespace(ckpt='/content/US-Transporter-eval/ckpt_TPRv1_LUS_radonbpm_lr0.0001_LUS_nossim_dptdecay_samrate10_VER_HORIZ_weightedHlam_radonbpm_-epoch=59-val_loss=0.00012.ckpt', device='cpu', frame_no=60, img='', vid='/content/US-Transporter-eval/WUS/011-wristDorSag-31L-5.mp4')
Initial Hlam weights are: Parameter containing:
tensor([[[[0.1000]],

         [[0.1000]],

         [[0.1000]],

         [[0.1000]],

         [[0.1000]],

         [[0.1000]],

         [[0.1000]],

         [[0.1000]],

         [[0.1000]],

         [[0.1000]]]], requires_grad=True)
torch.Size([3, 256, 256])
torch.Size([3, 256, 256])
torch.Size([3, 256, 256])
returned
recieved_vid_frame
output/frame60011-wristDorSag-31L-5.jpg
